/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MythRouteImport } from './routes/myth'
import { Route as ImproveRouteImport } from './routes/improve'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'

const MythRoute = MythRouteImport.update({
  id: '/myth',
  path: '/myth',
  getParentRoute: () => rootRouteImport,
} as any)
const ImproveRoute = ImproveRouteImport.update({
  id: '/improve',
  path: '/improve',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/guide': typeof GuideRoute
  '/improve': typeof ImproveRoute
  '/myth': typeof MythRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/guide': typeof GuideRoute
  '/improve': typeof ImproveRoute
  '/myth': typeof MythRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/guide': typeof GuideRoute
  '/improve': typeof ImproveRoute
  '/myth': typeof MythRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chat' | '/guide' | '/improve' | '/myth'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chat' | '/guide' | '/improve' | '/myth'
  id: '__root__' | '/' | '/chat' | '/guide' | '/improve' | '/myth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  GuideRoute: typeof GuideRoute
  ImproveRoute: typeof ImproveRoute
  MythRoute: typeof MythRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/myth': {
      id: '/myth'
      path: '/myth'
      fullPath: '/myth'
      preLoaderRoute: typeof MythRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/improve': {
      id: '/improve'
      path: '/improve'
      fullPath: '/improve'
      preLoaderRoute: typeof ImproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  GuideRoute: GuideRoute,
  ImproveRoute: ImproveRoute,
  MythRoute: MythRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
